[package]
name = "gem-knight"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
heapless = "0.7.16"
itertools = "0.10.5"
rand = { version = "0.8.5", features = ["small_rng"] }
